## WiSHFUL Agent config file

agent_info:
  name: 'wishful_simple_agent_123'
  info: 'wishful_simple_agent_info'


inproc_modules:
  ath9k_module_inproc:
      type : python
      import : wishful_ath9k_driver
      class_name : Ath9kDriver
      args : ['-i wlan0,wlan1']
      function: process_msgs
      message_type : [WIFI, RADIO, ALL]


modules:
  ath9k_module_outproc:
      type : python
      path : ../../wishful_module_ath9k/bin/ath9k_driver
      args : ['-i wlan0,wlan1']
      message_type : [WIFI, RADIO, ALL]

  discovery_module:
      type : python
      path : ../../wishful_module_discovery/bin/simple_discovery
      args : ['-d tcp://127.0.0.1:8989', '-u tcp://127.0.0.1:8990']
      message_type : [DISCOVERY]

  synchronization_module:
      type : python
      path : ../../wishful_module_ptp/bin/ptp_client.py
      args : ['-i eth0']
      message_type : []

  iperf_module:
      type : python
      path : ../../wishful_module_iperf/bin/iperf_driver
      args : ['']
      message_type : [PERFORMANCE_TEST, ALL]